language: go
go:
  - "1.12"
  - "1.11.x"
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - i@leeif.ma
    on_success: change # default: change
    on_failure: always # default: always

before_install:
  - go test -cpu=1,2,4 -v -tags integration ./...
  - go vet $(go list ./... | grep -v /vendor/)

script:
  - make fmt
  - make fmt-check
  - make vet
  - make list  
  - go test -race  ./... -coverprofile=coverage.txt -covermode=atomic